module.exports = {
  projectName: 'vue-element',
  privateKey: 'C:\\Users\\Administrator/.ssh/id_rsa',
  passphrase: '',
  cluster: [],
  dev: {
    name: '开发环境',
    script: 'npm run build:dev',
    host: '127.0.0.1',
    port: 22,
    username: 'root',
    password: '123456',
    distPath: 'dist',
    webDir: '/',
    bakDir: '/',
    isRemoveRemoteFile: true,
    isRemoveLocalFile: true,
  },
  test: {
    name: '测试环境',
    script: 'npm run build:test',
    host: '',
    port: 22,
    username: 'root',
    password: '123456',
    distPath: 'dist',
    webDir: '/',
    bakDir: '/',
    isRemoveRemoteFile: true,
    isRemoveLocalFile: true,
  },
  prod: {
    name: '生产环境',
    script: 'npm run build:prod',
    host: '',
    port: 22,
    username: 'root',
    password: '',
    distPath: 'dist',
    webDir: '',
    bakDir: '',
    isRemoveRemoteFile: true,
    isRemoveLocalFile: true,
  },
}
